# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: capruk
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

volumes:
  dbdata:
  redisdata: