BINARY_NAME=caprukApp

build:
	@go mod vendor
	@echo "Building Capruk..."
	@go build -o tmp/${BINARY_NAME} .
	@echo "Capruk built!"

run: build
	@echo "Starting Capruk..."
	@./tmp/${BINARY_NAME} &
	@echo "Capruk started!"

clean:
	@echo "Cleaning..."
	@go clean
	@rm tmp/${BINARY_NAME}
	@echo "Cleaned!"

test:
	@echo "Testing..."
	@go test ./...
	@echo "Done!"

start: run

stop:
	@echo "Stopping Capruk..."
	@-pkill -SIGTERM -f "./tmp/${BINARY_NAME}"
	@echo "Stopped Capruk!"

restart: stop start